### PR TITLE
feat(release.sh): remove hardcoded 'v2-beta' tag so unique comes through

### PR DESCRIPTION
**Pull request by vdice**
As part of the immutable image promotion effort for logger

### CODE REVIEW

**Comment by jchauncey** [comment]
so `deploy.sh` is already creating images with git-shas and uploading them quay and docker hug under the deisci org

**Comment by vdice** [comment]
Ah, so is `release.sh` not being used?

**Comment by jchauncey** [comment]
release isnt used by CI right now. I use it when I need to cut new v2-beta images for logger.

**Comment by vdice** [comment]
Gotcha; closing.

**Pull request closed without merging**
