### PR TITLE
chore(deploy.sh): Should run make build push

### PR DESCRIPTION
**Pull request by jchauncey**

### CODE REVIEW

**Comment by arschles** [comment]
I don't think this will work when the deploy script is run unless you change the `language` field to `go`. See https://github.com/deis/logger/blob/master/.travis.yml#L1

**Comment by jchauncey** [comment]
why

**Comment by arschles** [comment]
@jchauncey nevermind, I misread what the `build` target does. code LGTM

**Comment by jchauncey** [comment]
haha alright =)

**Pull request merged**
